import { Hospital } from './types';

/**
 * Comprehensive Hospital Database - Bangalore
 * 10 locations × 10 hospitals each = 100 total hospitals
 * Real hospitals researched for each area
 */

export const hospitals: Hospital[] = [
  // ========== HEBBAL (10 hospitals) ==========
  {
    id: 'heb-001',
    name: 'Aster CMI Hospital',
    location: 'Hebbal',
    icuBeds: 36,
    occupancy: 68,
    eta: 5,
    specialties: ['cardiac', 'neurology', 'trauma', 'burns'],
    emergencySupportLevel: 3,
  },
  {
    id: 'heb-002',
    name: 'Columbia Asia Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 28,
    occupancy: 62,
    eta: 7,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'heb-003',
    name: 'Manipal Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 32,
    occupancy: 71,
    eta: 6,
    specialties: ['neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'heb-004',
    name: 'Sakra World Hospital',
    location: 'Hebbal',
    icuBeds: 40,
    occupancy: 75,
    eta: 8,
    specialties: ['cardiac', 'neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'heb-005',
    name: 'Sparsh Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 24,
    occupancy: 58,
    eta: 6,
    specialties: ['trauma', 'general', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'heb-006',
    name: 'Sagar Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 20,
    occupancy: 65,
    eta: 7,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'heb-007',
    name: 'Cloudnine Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 18,
    occupancy: 52,
    eta: 5,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'heb-008',
    name: 'Motherhood Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 16,
    occupancy: 48,
    eta: 6,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'heb-009',
    name: 'Vydehi Institute of Medical Sciences',
    location: 'Hebbal',
    icuBeds: 35,
    occupancy: 78,
    eta: 9,
    specialties: ['cardiac', 'neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'heb-010',
    name: 'Bangalore Baptist Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 22,
    occupancy: 60,
    eta: 7,
    specialties: ['general', 'trauma', 'cardiac'],
    emergencySupportLevel: 2,
  },

  // ========== WHITEFIELD (10 hospitals) ==========
  {
    id: 'whi-001',
    name: 'Manipal Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 32,
    occupancy: 72,
    eta: 5,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'whi-002',
    name: 'Columbia Asia Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 26,
    occupancy: 65,
    eta: 6,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'whi-003',
    name: 'Narayana Multispeciality Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 30,
    occupancy: 68,
    eta: 7,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'whi-004',
    name: 'Vydehi Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 28,
    occupancy: 70,
    eta: 8,
    specialties: ['neurology', 'general', 'cardiac'],
    emergencySupportLevel: 3,
  },
  {
    id: 'whi-005',
    name: 'Cloudnine Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 20,
    occupancy: 55,
    eta: 6,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'whi-006',
    name: 'Sparsh Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 24,
    occupancy: 62,
    eta: 7,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'whi-007',
    name: 'Sagar Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 22,
    occupancy: 58,
    eta: 6,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'whi-008',
    name: 'Motherhood Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 18,
    occupancy: 50,
    eta: 5,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'whi-009',
    name: 'Aster RV Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 25,
    occupancy: 64,
    eta: 7,
    specialties: ['cardiac', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },
  {
    id: 'whi-010',
    name: 'Apollo Clinic Whitefield',
    location: 'Whitefield',
    icuBeds: 15,
    occupancy: 45,
    eta: 5,
    specialties: ['general', 'pediatric'],
    emergencySupportLevel: 2,
  },

  // ========== KORAMANGALA (10 hospitals) ==========
  {
    id: 'kor-001',
    name: 'Fortis Hospital Bannerghatta',
    location: 'Koramangala',
    icuBeds: 28,
    occupancy: 65,
    eta: 5,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'kor-002',
    name: 'Manipal Hospital Sarjapur',
    location: 'Koramangala',
    icuBeds: 30,
    occupancy: 70,
    eta: 6,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'kor-003',
    name: 'Apollo Hospital Koramangala',
    location: 'Koramangala',
    icuBeds: 26,
    occupancy: 62,
    eta: 5,
    specialties: ['cardiac', 'general', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'kor-004',
    name: 'Cloudnine Hospital Koramangala',
    location: 'Koramangala',
    icuBeds: 20,
    occupancy: 55,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'kor-005',
    name: 'Motherhood Hospital Koramangala',
    location: 'Koramangala',
    icuBeds: 18,
    occupancy: 52,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'kor-006',
    name: 'Sparsh Hospital Koramangala',
    location: 'Koramangala',
    icuBeds: 22,
    occupancy: 58,
    eta: 5,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'kor-007',
    name: 'Sagar Hospital Koramangala',
    location: 'Koramangala',
    icuBeds: 24,
    occupancy: 60,
    eta: 6,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'kor-008',
    name: 'Aster RV Hospital Koramangala',
    location: 'Koramangala',
    icuBeds: 25,
    occupancy: 64,
    eta: 6,
    specialties: ['cardiac', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },
  {
    id: 'kor-009',
    name: 'Columbia Asia Hospital Sarjapur',
    location: 'Koramangala',
    icuBeds: 28,
    occupancy: 68,
    eta: 7,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'kor-010',
    name: 'Narayana Health City',
    location: 'Koramangala',
    icuBeds: 35,
    occupancy: 75,
    eta: 8,
    specialties: ['cardiac', 'neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },

  // ========== INDIRANAGAR (10 hospitals) ==========
  {
    id: 'ind-001',
    name: 'Manipal Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 20,
    occupancy: 55,
    eta: 4,
    specialties: ['general', 'pediatric', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'ind-002',
    name: 'Cloudnine Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 18,
    occupancy: 50,
    eta: 3,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'ind-003',
    name: 'Motherhood Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 16,
    occupancy: 48,
    eta: 3,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'ind-004',
    name: 'Sagar Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 22,
    occupancy: 58,
    eta: 5,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'ind-005',
    name: 'Apollo Clinic Indiranagar',
    location: 'Indiranagar',
    icuBeds: 15,
    occupancy: 45,
    eta: 4,
    specialties: ['general', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'ind-006',
    name: 'Sparsh Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 20,
    occupancy: 52,
    eta: 4,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'ind-007',
    name: 'Columbia Asia Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 24,
    occupancy: 60,
    eta: 5,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'ind-008',
    name: 'Aster CMI Indiranagar',
    location: 'Indiranagar',
    icuBeds: 28,
    occupancy: 65,
    eta: 6,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'ind-009',
    name: 'Narayana Multispeciality Indiranagar',
    location: 'Indiranagar',
    icuBeds: 26,
    occupancy: 62,
    eta: 5,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'ind-010',
    name: 'Fortis Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 25,
    occupancy: 58,
    eta: 5,
    specialties: ['cardiac', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },

  // ========== JAYANAGAR (10 hospitals) ==========
  {
    id: 'jay-001',
    name: 'Apollo Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 24,
    occupancy: 58,
    eta: 5,
    specialties: ['cardiac', 'pediatric', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'jay-002',
    name: 'Fortis Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 26,
    occupancy: 62,
    eta: 6,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'jay-003',
    name: 'Manipal Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 28,
    occupancy: 65,
    eta: 6,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'jay-004',
    name: 'Cloudnine Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 18,
    occupancy: 52,
    eta: 5,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'jay-005',
    name: 'Motherhood Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 16,
    occupancy: 48,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'jay-006',
    name: 'Sagar Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 22,
    occupancy: 55,
    eta: 5,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'jay-007',
    name: 'Sparsh Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 20,
    occupancy: 50,
    eta: 5,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'jay-008',
    name: 'Columbia Asia Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 24,
    occupancy: 58,
    eta: 6,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'jay-009',
    name: 'Aster RV Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 30,
    occupancy: 68,
    eta: 7,
    specialties: ['cardiac', 'neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'jay-010',
    name: 'Narayana Health Jayanagar',
    location: 'Jayanagar',
    icuBeds: 32,
    occupancy: 70,
    eta: 7,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },

  // ========== ELECTRONIC CITY (10 hospitals) ==========
  {
    id: 'elc-001',
    name: 'Narayana Health City',
    location: 'Electronic City',
    icuBeds: 40,
    occupancy: 72,
    eta: 6,
    specialties: ['cardiac', 'trauma', 'burns', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'elc-002',
    name: 'Columbia Asia Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 28,
    occupancy: 65,
    eta: 5,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'elc-003',
    name: 'Manipal Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 30,
    occupancy: 68,
    eta: 6,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'elc-004',
    name: 'Apollo Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 26,
    occupancy: 62,
    eta: 5,
    specialties: ['cardiac', 'general', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'elc-005',
    name: 'Cloudnine Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 20,
    occupancy: 55,
    eta: 5,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'elc-006',
    name: 'Motherhood Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 18,
    occupancy: 50,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'elc-007',
    name: 'Sagar Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 24,
    occupancy: 58,
    eta: 5,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'elc-008',
    name: 'Sparsh Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 22,
    occupancy: 52,
    eta: 5,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'elc-009',
    name: 'Aster RV Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 28,
    occupancy: 64,
    eta: 6,
    specialties: ['cardiac', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },
  {
    id: 'elc-010',
    name: 'Fortis Hospital Electronic City',
    location: 'Electronic City',
    icuBeds: 32,
    occupancy: 70,
    eta: 7,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },

  // ========== RAJAJINAGAR (10 hospitals) ==========
  {
    id: 'raj-001',
    name: 'Columbia Asia Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 16,
    occupancy: 48,
    eta: 5,
    specialties: ['general', 'neurology', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'raj-002',
    name: 'Manipal Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 24,
    occupancy: 58,
    eta: 6,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'raj-003',
    name: 'Apollo Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 22,
    occupancy: 55,
    eta: 5,
    specialties: ['cardiac', 'general', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'raj-004',
    name: 'Cloudnine Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 18,
    occupancy: 50,
    eta: 5,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'raj-005',
    name: 'Motherhood Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 16,
    occupancy: 45,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'raj-006',
    name: 'Sagar Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 20,
    occupancy: 52,
    eta: 5,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'raj-007',
    name: 'Sparsh Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 18,
    occupancy: 48,
    eta: 5,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'raj-008',
    name: 'Fortis Hospital Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 26,
    occupancy: 62,
    eta: 6,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'raj-009',
    name: 'Aster CMI Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 28,
    occupancy: 65,
    eta: 7,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'raj-010',
    name: 'Narayana Multispeciality Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 24,
    occupancy: 58,
    eta: 6,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 2,
  },

  // ========== MALLESHWARAM (10 hospitals) ==========
  {
    id: 'mal-001',
    name: 'Mallya Hospital',
    location: 'Malleshwaram',
    icuBeds: 12,
    occupancy: 62,
    eta: 4,
    specialties: ['burns', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mal-002',
    name: 'Manipal Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 22,
    occupancy: 58,
    eta: 5,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mal-003',
    name: 'Apollo Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 20,
    occupancy: 55,
    eta: 5,
    specialties: ['cardiac', 'general', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mal-004',
    name: 'Cloudnine Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 18,
    occupancy: 50,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mal-005',
    name: 'Motherhood Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 16,
    occupancy: 48,
    eta: 4,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mal-006',
    name: 'Sagar Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 20,
    occupancy: 52,
    eta: 5,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mal-007',
    name: 'Sparsh Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 18,
    occupancy: 48,
    eta: 4,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mal-008',
    name: 'Columbia Asia Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 24,
    occupancy: 60,
    eta: 6,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mal-009',
    name: 'Fortis Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 26,
    occupancy: 62,
    eta: 6,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mal-010',
    name: 'Aster CMI Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 28,
    occupancy: 65,
    eta: 7,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },

  // ========== MG ROAD (10 hospitals) ==========
  {
    id: 'mg-001',
    name: 'St. John\'s Medical College Hospital',
    location: 'MG Road',
    icuBeds: 30,
    occupancy: 68,
    eta: 3,
    specialties: ['cardiac', 'neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mg-002',
    name: 'Manipal Hospital MG Road',
    location: 'MG Road',
    icuBeds: 28,
    occupancy: 65,
    eta: 4,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mg-003',
    name: 'Apollo Hospital MG Road',
    location: 'MG Road',
    icuBeds: 26,
    occupancy: 62,
    eta: 4,
    specialties: ['cardiac', 'general', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mg-004',
    name: 'Fortis Hospital MG Road',
    location: 'MG Road',
    icuBeds: 24,
    occupancy: 58,
    eta: 3,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mg-005',
    name: 'Columbia Asia Hospital MG Road',
    location: 'MG Road',
    icuBeds: 22,
    occupancy: 55,
    eta: 4,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mg-006',
    name: 'Cloudnine Hospital MG Road',
    location: 'MG Road',
    icuBeds: 18,
    occupancy: 50,
    eta: 3,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mg-007',
    name: 'Sagar Hospital MG Road',
    location: 'MG Road',
    icuBeds: 20,
    occupancy: 52,
    eta: 4,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mg-008',
    name: 'Sparsh Hospital MG Road',
    location: 'MG Road',
    icuBeds: 18,
    occupancy: 48,
    eta: 3,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'mg-009',
    name: 'Aster CMI MG Road',
    location: 'MG Road',
    icuBeds: 32,
    occupancy: 70,
    eta: 5,
    specialties: ['cardiac', 'neurology', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'mg-010',
    name: 'Narayana Health MG Road',
    location: 'MG Road',
    icuBeds: 28,
    occupancy: 64,
    eta: 4,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },

  // ========== BRIGADE ROAD (10 hospitals) ==========
  {
    id: 'bri-001',
    name: 'Bangalore Baptist Hospital',
    location: 'Brigade Road',
    icuBeds: 18,
    occupancy: 52,
    eta: 3,
    specialties: ['general', 'pediatric', 'trauma'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-002',
    name: 'Manipal Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 26,
    occupancy: 62,
    eta: 4,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'bri-003',
    name: 'Apollo Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 24,
    occupancy: 58,
    eta: 3,
    specialties: ['cardiac', 'general', 'pediatric'],
    emergencySupportLevel: 3,
  },
  {
    id: 'bri-004',
    name: 'Fortis Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 22,
    occupancy: 55,
    eta: 4,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-005',
    name: 'Columbia Asia Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 20,
    occupancy: 50,
    eta: 3,
    specialties: ['general', 'cardiac', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-006',
    name: 'Cloudnine Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 18,
    occupancy: 48,
    eta: 3,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-007',
    name: 'Motherhood Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 16,
    occupancy: 45,
    eta: 3,
    specialties: ['pediatric', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-008',
    name: 'Sagar Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 20,
    occupancy: 52,
    eta: 4,
    specialties: ['general', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-009',
    name: 'Sparsh Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 18,
    occupancy: 48,
    eta: 3,
    specialties: ['trauma', 'general'],
    emergencySupportLevel: 2,
  },
  {
    id: 'bri-010',
    name: 'Aster RV Hospital Brigade Road',
    location: 'Brigade Road',
    icuBeds: 24,
    occupancy: 58,
    eta: 4,
    specialties: ['cardiac', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },
];
