import { Hospital } from './types';

export const hospitals: Hospital[] = [
  {
    id: 'hosp-001',
    name: 'Manipal Hospital Whitefield',
    location: 'Whitefield',
    icuBeds: 32,
    occupancy: 72,
    eta: 42,
    specialties: ['cardiac', 'neurology', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'hosp-002',
    name: 'Fortis Hospital Bannerghatta',
    location: 'Koramangala',
    icuBeds: 28,
    occupancy: 65,
    eta: 18,
    specialties: ['cardiac', 'trauma', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'hosp-003',
    name: 'Apollo Hospital Jayanagar',
    location: 'Jayanagar',
    icuBeds: 24,
    occupancy: 58,
    eta: 22,
    specialties: ['cardiac', 'pediatric', 'general'],
    emergencySupportLevel: 3,
  },
  {
    id: 'hosp-004',
    name: 'Aster CMI Hospital Hebbal',
    location: 'Hebbal',
    icuBeds: 36,
    occupancy: 78,
    eta: 28,
    specialties: ['trauma', 'neurology', 'burns'],
    emergencySupportLevel: 3,
  },
  {
    id: 'hosp-005',
    name: 'Manipal Hospital Indiranagar',
    location: 'Indiranagar',
    icuBeds: 20,
    occupancy: 55,
    eta: 15,
    specialties: ['general', 'pediatric', 'cardiac'],
    emergencySupportLevel: 2,
  },
  {
    id: 'hosp-006',
    name: 'Narayana Health City Electronic City',
    location: 'Electronic City',
    icuBeds: 40,
    occupancy: 82,
    eta: 38,
    specialties: ['cardiac', 'trauma', 'burns'],
    emergencySupportLevel: 3,
  },
  {
    id: 'hosp-007',
    name: 'Columbia Asia Rajajinagar',
    location: 'Rajajinagar',
    icuBeds: 16,
    occupancy: 48,
    eta: 25,
    specialties: ['general', 'neurology', 'pediatric'],
    emergencySupportLevel: 2,
  },
  {
    id: 'hosp-008',
    name: 'Mallya Hospital Malleshwaram',
    location: 'Malleshwaram',
    icuBeds: 12,
    occupancy: 62,
    eta: 20,
    specialties: ['burns', 'general', 'trauma'],
    emergencySupportLevel: 2,
  },
];
